name: docker-build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag (optional)'
        required: false
        type: string

env:
  DOCKERHUB_REPO: giterhub/certimate

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
      GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'certimate-go'
          repository: 'certimate'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DeckerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ github.event.inputs.version && format('{0}:{1}', env.DOCKERHUB_REPO, github.event.inputs.version) || '' }}
          platforms: |
            linux/amd64
      - name: Send notification
        if: ${{ !cancelled() && env.GOTIFY_URL != '' && env.GOTIFY_TOKEN != '' }}
        uses: dragonish/send-to-gotify@v1
        with:
          url: ${{ secrets.GOTIFY_URL }}
          token: ${{ secrets.GOTIFY_TOKEN }}
          title: ${{ github.repository }}
          message: "Build ${{ github.event.inputs.version && format('{0}:{1}', env.DOCKERHUB_REPO, github.event.inputs.version) || format('{0}:{1}', env.DOCKERHUB_REPO, 'latest') }}\n\n*status: ${{ job.status }}*"
          content-type: 'text/markdown'
