name: docker-build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version tag (optional)'
        required: false
        type: string

env:
  DOCKERHUB_REPO: giterhub/certimate

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      NTFY_URL: ${{ secrets.NTFY_URL }}
      NTFY_TOKEN: ${{ secrets.NTFY_TOKEN }}
      NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Clone Repository
        run: |
          git clone https://github.com/certimate-go/certimate.git

          cd certimate

          git config -f .gitmodules submodule.pkg/sdk3rd-forked.url https://github.com/certimate-go/.deps-repo-go.git

          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to DeckerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ github.event.inputs.version && format('{0}:{1}', env.DOCKERHUB_REPO, github.event.inputs.version) || '' }}
          platforms: |
            linux/amd64
      - name: Send notification
        if: ${{ !cancelled() && env.NTFY_URL != '' && env.NTFY_TOKEN != '' && env.NTFY_TOPIC != '' }}
        uses: dragonish/send-to-ntfy@v1
        with:
          base-url: ${{ secrets.NTFY_URL }}
          topic: ${{ secrets.NTFY_TOPIC }}
          access-token: ${{ secrets.NTFY_TOKEN }}
          title: ${{ github.repository }}
          message: "Build ${{ github.event.inputs.version && format('{0}:{1}', env.DOCKERHUB_REPO, github.event.inputs.version) || format('{0}:{1}', env.DOCKERHUB_REPO, 'latest') }}"
          tags: "GitHub,Docker,building_construction,${{ job.status }}"
          priority: 2
          actions: '[{"action": "view", "label": "View GitHub", "url": "https://github.com/${{ github.repository }}"}, {"action": "view", "label": "View Docker Hub", "url": "https://hub.docker.com/r/${{ env.DOCKERHUB_REPO }}"}]'
